### ISSUE TITLE
Add option to the CLI to suppress the "No syntax errors" message

### ISSUE THREAD

**Issue by tobiastom** [wayneashleyberry/phplint#20]
It might be night to only display something when there was an error.

**Comment by wayneashleyberry** [comment]
Yeah, this would be great... I'll get on it @tobiastom :)

**Comment by Soullivaneuh** [comment]
Great :+1: for this.

**Comment by wayneashleyberry** [comment]
Added `--suppress` or `-s` for short in [v1.7.0](https://github.com/wayneashleyberry/phplint/releases/tag/v1.7.0)

**Comment by tobiastom** [comment]
Works for me. Thanks @wayneashleyberry for implementing it!

**Comment by tobiastom** [comment]
Works for me. Thank you for implementing it @wayneashleyberry.
