### ISSUE TITLE
phpCmd not handled by grunt

### ISSUE THREAD

**Issue by fboutin-pmc** [wayneashleyberry/phplint#25]
It works with `gulp` but grunt will simply ignore the `phpCmd` option.

**Comment by nabhacosley** [comment]
I'm having a similar / the same issue. I get this when running `grunt phplint`:

    Warning: Command failed: php -d display_errors=1 -l functions/enqueue.php
     Use --force to continue.

... even when phpCmd is set to the right path.

**Comment by wayneashleyberry** [comment]
Sorry about this @fboutin-pmc and @nabhacosley - I'll try and have a look at it over the weekend.

**Comment by nabhacosley** [comment]
It's very kind of you to maintain this. I'm actually still able to use it even without the detailed error reporting that comes from the PHP command.

**Comment by fboutin-pmc** [comment]
TBH, we finally ended-up with gulp, ditching grunt... which is not a bad thing in the end ;)

**Comment by wayneashleyberry** [comment]
This should be fixed in [v1.7.3](https://github.com/wayneashleyberry/phplint/releases/tag/v1.7.3).
