### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by fboutin-pmc** [wayneashleyberry/phplint#27]
Hi there,
I replaced the `phpCmd` with `hhvm` and the script fails when "spawing" the process because of the `-v` switch.

I tried passing `hhvm --php` so the `-v` option would be supported but without success.

I think that, instead of passing `-v`, we should use the `--version` switch or make it configurable somehow.

Thank you,

**Comment by wayneashleyberry** [comment]
Unfortunately I only plan on supporting php :)

**Comment by fboutin-pmc** [comment]
Wtf... we simply have to use `--version` instead of `-v`.
