### ISSUE TITLE
config json to set options

### ISSUE THREAD

**Issue by axtho** [wayneashleyberry/phplint#29]
Other linters (like tslint) have the option to create a .json to define what the code checker should check for (eol, whitespaces, class constructors, etc.). I cannot see this here. Is that possible, or planned?

**Comment by wayneashleyberry** [comment]
Hi @axtho, I'm just wrapping PHP's native linter - which can only lint one file at a time and has no configuration options. You might want to check out something like https://github.com/squizlabs/PHP_CodeSniffer which checks actualy coding style :)
