### ISSUE TITLE
If I want disable 'print_r' in a php file, how can I do that?

### ISSUE THREAD

**Issue by xielehe** [wayneashleyberry/phplint#33]
I want phplint warnning me when that happen,what should I do?

**Comment by wayneashleyberry** [comment]
Hey @xielehe - the php linter doesn't have any configuration options unfortunately.

You'll be better off using a different tool to enforce coding standards. [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) has a ruleset for this, but I'm not sure if it's enabled by default.

```xml
 <!--
    Array values are specified by using a string
    representation of the array.
 -->
 <rule ref="Generic.PHP.ForbiddenFunctions">
  <properties>
   <property name="forbiddenFunctions" type="array" value="delete=>unset,print=>echo,create_function=>null" />
  </properties>
 </rule>
```

Taken from https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml
